apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: rap-analyzer
  labels:
    app: grafana
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-service:9090
        access: proxy
        isDefault: true
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: rap-analyzer
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-rap-analyzer
  namespace: rap-analyzer
  labels:
    app: grafana
data:
  rap-analyzer-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Rap Analyzer Metrics",
        "tags": ["rap-analyzer"],
        "style": "dark",
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
            "title": "Request Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "rate(http_requests_total[5m])",
                "refId": "A"
              }
            ],
            "options": {
              "reduceOptions": {
                "values": false,
                "calcs": ["lastNotNull"],
                "fields": ""
              },
              "orientation": "auto",
              "textMode": "auto",
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto"
            },
            "pluginVersion": "9.0.0"
          },
          {
            "id": 2,
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
            "title": "Error Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "rate(http_requests_total{status=~\"5..\"}[5m])",
                "refId": "A"
              }
            ],
            "options": {
              "reduceOptions": {
                "values": false,
                "calcs": ["lastNotNull"],
                "fields": ""
              },
              "orientation": "auto",
              "textMode": "auto",
              "colorMode": "value",
              "graphMode": "area",
              "justifyMode": "auto"
            },
            "pluginVersion": "9.0.0"
          },
          {
            "id": 3,
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8},
            "title": "Request Duration",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
                "refId": "A",
                "legendFormat": "95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket[5m]))",
                "refId": "B",
                "legendFormat": "50th percentile"
              }
            ],
            "yAxes": [
              {
                "label": "seconds",
                "show": true
              },
              {
                "show": true
              }
            ],
            "xAxis": {
              "show": true
            },
            "legend": {
              "show": true
            }
          },
          {
            "id": 4,
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 16},
            "title": "Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{pod=~\"rap-analyzer-.*\"} / 1024 / 1024",
                "refId": "A",
                "legendFormat": "{{pod}}"
              }
            ],
            "yAxes": [
              {
                "label": "MB",
                "show": true
              },
              {
                "show": true
              }
            ]
          },
          {
            "id": 5,
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 16},
            "title": "CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{pod=~\"rap-analyzer-.*\"}[5m]) * 100",
                "refId": "A",
                "legendFormat": "{{pod}}"
              }
            ],
            "yAxes": [
              {
                "label": "percent",
                "show": true
              },
              {
                "show": true
              }
            ]
          },
          {
            "id": 6,
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 24},
            "title": "Database Connections",
            "type": "graph",
            "targets": [
              {
                "expr": "pg_stat_database_numbackends{datname=\"rap_lyrics\"}",
                "refId": "A",
                "legendFormat": "Active Connections"
              }
            ],
            "yAxes": [
              {
                "label": "connections",
                "show": true
              },
              {
                "show": true
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: rap-analyzer
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        runAsUser: 472
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        ports:
        - containerPort: 3000
          name: http-grafana
          protocol: TCP
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin123
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        - name: GF_ANALYTICS_REPORTING_ENABLED
          value: "false"
        - name: GF_ANALYTICS_CHECK_FOR_UPDATES
          value: "false"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /robots.txt
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pv
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards-config
          readOnly: false
        - mountPath: /var/lib/grafana/dashboards
          name: grafana-dashboard-rap-analyzer
          readOnly: false
      volumes:
      - name: grafana-pv
        emptyDir: {}
      - name: grafana-datasources
        configMap:
          defaultMode: 420
          name: grafana-datasources
      - name: grafana-dashboards-config
        configMap:
          defaultMode: 420
          name: grafana-dashboards-config
      - name: grafana-dashboard-rap-analyzer
        configMap:
          defaultMode: 420
          name: grafana-dashboard-rap-analyzer
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: rap-analyzer
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
    targetPort: http-grafana
  selector:
    app: grafana